<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config = array();
$config['Destination'] = array(
	'table' => 'destinations', 
	'audit' =>true,
  	'comment' => 'Store destination data of the system',
  	'fields' => array (
  		'id' => array (
		    'field'		=> 'id',
		    'label' 	=> 'ID',
		    'column'	=> 'id',		    
		    'type'		=> 'id',
		    'required'	=> true,		    	   
		    'comment' 	=> 'Unique identifier',
		),
		'name' => array (
		    'field'		=> 'name',
		    'label' 	=> 'lang:des_fields_name',
		    'column'	=> 'name',
		    'type'		=> 'varchar',
		    'len'		=> 50,	    
		    'required'	=> true,
		    'rules'		=> 'required|callback__name_check',
		    'comment' 	=> 'name of destination',
		),
		
		'is_top' 	=> array (
		    'field'		=> 'is_top',
		    'label' 	=> 'lang:des_fields_istop',
		    'column'	=> 'is_top',
		    'type'		=> 'tinyint',
		    'len'		=> 1,	    
		    'required'	=> false,
		    'rules'		=> '',
		    'comment' 	=> 'des is top',
		),		
		'region' 	=> array (
		    'field'		=> 'region',
		    'label' 	=> 'lang:des_fields_region',
		    'column'	=> 'region',
		    'type'		=> 'tinyint',
		    'len'		=> 1,	    
		    'required'	=> false,
			'rules'		=> 'required',
		    'comment' 	=> 'region of des',
		),		
		'picture' 	=> array (
		    'field'		=> 'picture',
		    'label' 	=> 'lang:des_fields_picture',
		    'column'	=> 'picture_name',
		    'type'		=> 'varchar',
		    'len'		=> 20,	    
		    'required'	=> true,
		    'rules'		=> '',
		    'comment' 	=> 'the picture of des',
		),		
		'order_' 	=> array (
		    'field'		=> 'order_',
		    'label' 	=> 'lang:des_fields_order_',
		    'column'	=> 'order_',
		    'type'		=> 'int',
		    'len'		=> 11,	    
		    'required'	=> false,
		    'comment' 	=> 'order of destination in des list',
		),		
		'general_info' 	=> array (
		    'field'		=> 'general_info',
		    'label' 	=> 'lang:des_fields_generalinfo',
		    'column'	=> 'general_info',
		    'type'		=> 'varchar',
		    'len'		=> 200,	    
		    'required'	=> true,
		    'rules'		=> 'required|max_length[200]',
		    'comment' 	=> 'the general infomation of des',
		),		
		'detail_info' 	=> array (
		    'field'		=> 'detail_info',
		    'label' 	=> 'lang:des_fields_detailinfo',
		    'column'	=> 'detail_info',
		    'type'		=> 'text',
		    'required'	=> true,
		    'rules'		=> 'required',
		    'comment' 	=> 'the detail infomation of des',
		),		
		'parent_id' 	=> array (
		    'field'		=> 'parent_id',
		    'label' 	=> 'lang:des_fields_parent',
		    'column'	=> 'parent_id',
		    'type'		=> 'int',
		    'required'	=> false,
		    'rules'		=> '',
		    'comment' 	=> 'the parent des of des',
		),
		'partner_id' 	=> array (
		    'field'		=> 'partner_id',
		    'label' 	=> 'partner_id',
		    'column'	=> 'partner_id',
		    'type'		=> 'int',
		    'required'	=> false,
		    'comment' 	=> 'the partner created this des',
		),		
		'type' 	=> array (
		    'field'		=> 'type',
		    'label' 	=> 'type',
		    'column'	=> 'type',
		    'type'		=> 'int',
		    'required'	=> true,
		    'comment' 	=> 'the type of des',
		),
		'user_created_id' 	=> array (
		    'field'		=> 'user_created_id',
		    'label' 	=> 'user_created_id',
		    'column'	=> 'user_created_id',
		    'type'		=> 'int',
		    'required'	=> true,
		    'comment' 	=> 'the user created this des',
		),
		'date_created' 	=> array (
		    'field'		=> 'date_created',
		    'label' 	=> 'date_created',
		    'column'	=> 'date_created',
		    'type'		=> 'datetime',
		    'required'	=> true,
		    'comment' 	=> 'the date this des was created',
		),
		'user_modified_id'	=> array (
		    'field'		=> 'user_modified_id',
		    'label' 	=> 'user_modified_id',
		    'column'	=> 'user_modified_id',
		    'type'		=> 'int',
		    'required'	=> true,
		    'comment' 	=> 'the user modified this des',
		),
		'date_modified' => array (
		    'field'		=> 'date_modified',
		    'label' 	=> 'date_modified',
		    'column'	=> 'date_modified',
		    'type'		=> 'datetime',
		    'required'	=> true,
		    'comment' 	=> 'the last modified of this',
		),
		'deleted' => array (
		    'field'		=> 'deleted',
		    'label' 	=> 'deleted',
		    'column'	=> 'deleted',
		    'type'		=> 'tinyint',
		    'required'	=> true,
		    'comment' 	=> 'mark deleted of this des',
		),
	)
);

$config['TourDestination'] = array(
	'table'	=> 'tour_destinations',
	'audit' => false,
  	'comment'	=> 'Store destinations of the tour',
  	'fields' => array (
  		'tour_id' => array (
		    'field'		=> 'tour_id',
		    'column'	=> 'tour_id',		    
		    'type'		=> 'int',
		    'comment' 	=> 'tour id',
		),
  		'destination_id' => array (
		    'field'		=> 'destination_id',
		    'column'	=> 'destination_id',		    
		    'type'		=> 'int',
		    'comment' 	=> 'destination id in the tour',
		),
		'order_' => array (
		    'field'		=> 'order_',
		    'column'	=> 'order_',
		    'type'		=> 'int',
		    'comment' 	=> 'the order of destinations in the tour',
		),
	),
);

/* End of file destination_meta.php */
/* Location: ./system/application/config/destination_meta.php */