<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config = array();
$config['Partner'] = array(
	'table' => 'partners', 
	'audit' =>true,
  	'comment' => 'Store partners of the system',
  	'fields' => array (
  		'id' => array (
		    'field'		=> 'id',
		    'label' 	=> 'ID',
		    'column'	=> 'id',		    
		    'type'		=> 'id',
		    'required'	=> true,		    	   
		    'comment' 	=> 'Unique identifier',
		),
		'name' => array (
		    'field'		=> 'name',
		    'label' 	=> 'lang:partner_fields_name',
		    'column'	=> 'name',
		    'type'		=> 'varchar',
		    'len'		=> 150,	    
		    'required'	=> true,
		    'rules'		=> 'required',
		    'comment' 	=> 'name of partner',
		),
		'short_name' 	=> array (
		    'field'		=> 'short_name',
		    'label' 	=> 'lang:partner_fields_short_name',
		    'column'	=> 'short_name',
		    'type'		=> 'varchar',
		    'len'		=> 50,	    
		    'required'	=> true,
		    'rules'		=> 'required',
		    'comment' 	=> 'short name of partner',
		),		
		'join_date' 	=> array (
		    'field'		=> 'join_date',
		    'label' 	=> 'lang:partner_fields_join_date',
		    'column'	=> 'join_date',
		    'type'		=> 'datetime',
		    'len'		=> 10,	    
		    'required'	=> true,
		    'rules'		=> 'required',
		    'comment' 	=> 'join date of partner',
		),		
		'phone' => array (
		    'column'	=> 'phone',
		    'field'		=> 'phone',
		    'label' 	=> 'lang:partner_fields_phone',
		    'type'		=> 'varchar',
		    'len'		=> 25,		    
		    'required'	=> true,		    
		    'audit'		=> true,
		    'rules'		=> 'required',
		    'comment' 	=> 'phone of partner',
		),
		'fax' => array (
		    'column'	=> 'fax',
		    'field'		=> 'fax',
		    'label' 	=> 'lang:partner_fields_fax',
		    'type'		=> 'varchar',
		    'len'		=> 25,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'fax of partner',
		),		
		'email' => array (
		    'column'	=> 'email',
		    'field'		=> 'email',
		    'label' 	=> 'lang:partner_fields_email',
		    'type'		=> 'varchar',
		    'len'		=> 100,
		    'required'	=> true,
		    'rules'		=> 'required|valid_email',
		    'audit'		=> true,		    
		    'comment' 	=> 'email of partner',
		),
		'website' => array (
		    'column'	=> 'website',
		    'field'		=> 'website',
		    'label' 	=> 'lang:partner_fields_website',
		    'type'		=> 'varchar',
		    'len'		=> 100,
		    'required'	=> true,
		    'rules'		=> 'required',
		    'audit'		=> true,		    
		    'comment' 	=> 'website of partner',
		),
		'address' => array (
		    'column'	=> 'address',
		    'field'		=> 'address',
		    'label' 	=> 'lang:partner_fields_address',
		    'type'		=> 'varchar',
		    'len'		=> 255,
		    'required'	=> true,
		    'rules'		=> 'required',
		    'audit'		=> true,		    
		    'comment' 	=> 'address of partner',
		),
		'contact1' => array (
		    'column'	=> 'contact1',
		    'field'		=> 'contact1',
		    'label' 	=> 'lang:partner_fields_contact1',
		    'type'		=> 'varchar',
		    'len'		=> 50,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'contact1 of partner',
		),
		'phone1' => array (
		    'column'	=> 'phone1',
		    'field'		=> 'phone1',
		    'label' 	=> 'lang:partner_fields_phone1',
		    'type'		=> 'varchar',
		    'len'		=> 25,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'phone1 of partner',
		),
		'mobile1' => array (
		    'column'	=> 'mobile1',
		    'field'		=> 'mobile1',
		    'label' 	=> 'lang:partner_fields_mobile1',
		    'type'		=> 'varchar',
		    'len'		=> 25,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'mobile1 of partner',
		),
		'email1' => array (
		    'column'	=> 'email1',
		    'field'		=> 'email1',
		    'label' 	=> 'lang:partner_fields_email1',
		    'type'		=> 'varchar',
		    'len'		=> 100,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'email1 of partner',
		),
		'contact2' => array (
		    'column'	=> 'contact2',
		    'field'		=> 'contact2',
		    'label' 	=> 'lang:partner_fields_contact2',
		    'type'		=> 'varchar',
		    'len'		=> 50,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'contact2 of partner',
		),
		'phone2' => array (
		    'column'	=> 'phone2',
		    'field'		=> 'phone2',
		    'label' 	=> 'lang:partner_fields_phone2',
		    'type'		=> 'varchar',
		    'len'		=> 25,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'phone2 of partner',
		),
		'mobile2' => array (
		    'column'	=> 'mobile2',
		    'field'		=> 'mobile2',
		    'label' 	=> 'lang:partner_fields_mobile2',
		    'type'		=> 'varchar',
		    'len'		=> 25,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'mobile2 of partner',
		),
		'email2' => array (
		    'column'	=> 'email2',
		    'field'		=> 'email2',
		    'label' 	=> 'lang:partner_fields_email2',
		    'type'		=> 'varchar',
		    'len'		=> 100,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'email2 of partner',
		),
		'date_created' => array (
		    'column'	=> 'date_created',
		    'field'		=> 'date_created',
		    'label' 	=> 'lang:partner_fields_date_created',
		    'type'		=> 'datetime',
		    'len'		=> 8,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'date_created of partner',
		),
		'user_created_id' => array (
		    'column'	=> 'user_created_id',
		    'field'		=> 'user_created_id',
		    'label' 	=> 'lang:partner_fields_user_created',
		    'type'		=> 'int',
		    'len'		=> 11,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'user_created of partner',
		),
		'date_modified' => array (
		    'column'	=> 'date_modified',
		    'field'		=> 'date_modified',
		    'label' 	=> 'lang:partner_fields_date_modified',
		    'type'		=> 'datetime',
		    'len'		=> 8,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'date_modified of partner',
		),
		'user_modified_id' => array (
		    'column'	=> 'user_modified_id',
		    'field'		=> 'user_modified_id',
		    'label' 	=> 'lang:partner_fields_user_modified',
		    'type'		=> 'int',
		    'len'		=> 11,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'user_modified of partner',
		),
		'deleted' => array (
		    'column'	=> 'deleted',
		    'field'		=> 'deleted',
		    'label' 	=> 'lang:partner_fields_deleted',
		    'type'		=> 'int',
		    'len'		=> 1,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'deleted of partner',
		),
	)
);

/* End of file partner_meta.php */
/* Location: ./system/application/config/partner_meta.php */