<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config = array();
$config['Promotion'] = array(
	'table' => 'promotions', 
	'audit' => true,
  	'comment' => 'Store promotions data of the system',
  	'fields' => array (
  		'id' => array (
		    'field'		=> 'id',
		    'label' 	=> 'ID',
		    'column'	=> 'id',		    
		    'type'		=> 'id',
		    'required'	=> true,		    	   
		    'comment' 	=> 'Unique identifier',
		),
		'name' => array (
		    'field'		=> 'name',
		    'label' 	=> 'lang:pro_fields_name',
		    'column'	=> 'name',
		    'type'		=> 'varchar',
		    'len'		=> 100,
		    'required'	=> true,
		    'rules'		=> 'required|callback__name_check',
		    'comment' 	=> 'name of promotion',
		),
		'start_date' 	=> array (
		    'field'		=> 'start_date',
		    'label' 	=> 'lang:pro_fields_startdate',
		    'column'	=> 'start_date',
		    'type'		=> 'datetime',
			'len'		=> 10,
		    'required'	=> true,
			'rules'		=> 'required|callback__is_date|callback__valid_date',
		    'comment' 	=> 'start date of promotion',
		),				
		'end_date' 	=> array (
		    'field'		=> 'end_date',
		    'label' 	=> 'lang:pro_fields_enddate',
		    'column'	=> 'end_date',
		    'type'		=> 'datetime',
		    'len'		=> 10,
		    'required'	=> true,		    
		    'rules'		=> 'required|callback__is_date',
		    'comment' 	=> 'end date of promotion',
		),				
		'status' 	=> array (
		    'field'		=> 'status',
		    'label' 	=> 'lang:pro_fields_status',
		    'column'	=> 'status',
		    'type'		=> 'tinyint',
		    'required'	=> true,
		    'rules'		=> '',
		    'comment' 	=> 'status of promotion',
		),		
		'note' 	=> array (
		    'field'		=> 'note',
		    'label' 	=> 'lang:pro_fields_note',
		    'column'	=> 'note',
		    'type'		=> 'varchar',
		    'len'		=> 500,
		    'required'	=> false,
		    'rules'		=> 'max_length[500]',
		    'comment' 	=> 'the note of promotion',
		),				
		'partner_id' 	=> array (
		    'field'		=> 'partner_id',
		    'label' 	=> 'lang:pro_fields_partner',
		    'column'	=> 'partner_id',
		    'type'		=> 'int',
		    'rules'		=> '',
		    'required'	=> false,
		    'comment' 	=> 'FK->partners',
		),		
		'user_created_id' 	=> array (
		    'field'		=> 'user_created_id',
		    'label' 	=> 'user_created_id',
		    'column'	=> 'user_created_id',
		    'type'		=> 'int',
		    'required'	=> true,
		    'comment' 	=> 'the id of user created this promotion',
		),
		'date_created' 	=> array (
		    'field'		=> 'date_created',
		    'label' 	=> 'date_created',
		    'column'	=> 'date_created',
		    'type'		=> 'datetime',
		    'required'	=> true,
		    'comment' 	=> 'the date this promotion was created',
		),
		'user_modified_id'	=> array (
		    'field'		=> 'user_modified_id',
		    'label' 	=> 'user_modified_id',
		    'column'	=> 'user_modified_id',
		    'type'		=> 'int',
		    'required'	=> true,
		    'comment' 	=> 'the id of user modified this promotion',
		),
		'date_modified' => array (
		    'field'		=> 'date_modified',
		    'label' 	=> 'date_modified',
		    'column'	=> 'date_modified',
		    'type'		=> 'datetime',
		    'required'	=> true,
		    'comment' 	=> 'the last modified of this promotion',
		),
		'deleted' => array (
		    'field'		=> 'deleted',
		    'label' 	=> 'deleted',
		    'column'	=> 'deleted',
		    'type'		=> 'tinyint',
		    'required'	=> true,
		    'comment' 	=> 'mark deleted of this promotion',
		),
		'specific_dates' 	=> array (
		    'field'		=> 'specific_dates',
		    'label' 	=> 'lang:pro_fields_specific_dates',
		    'column'	=> '',
		    'type'		=> 'varchar',
		    'len'		=> 1000,
		    'required'	=> false,
		    'rules'		=> 'max_length[1000]|callback__is_specific_dates',
		    'comment' 	=> 'the specific applied dates',
		),
	)
);

$config['PromotionDetail'] = array(
	'table'	=> 'promotion_details', 
	'audit' => true,
  	'comment'	=> 'Store details of a promotion',
  	'fields' => array (
  		'id' => array (
		    'field'		=> 'id',
		    'label' 	=> 'ID',
		    'column'	=> 'id',		    
		    'type'		=> 'id',
		    'required'	=> true,		    	   
		    'comment' 	=> 'Unique identifier',
		),
		'class_service' => array (
		    'field'		=> 'class_service',
		    'label' 	=> 'lang:pro_detail_offerrate',
		    'column'	=> 'class_service',
		    'type'		=> 'tinyint',		    
		    'required'	=> true,
		    'comment' 	=> 'class service for promotion',
		),
		'note' => array (
		    'field'		=> 'note',
		    'label' 	=> 'lang:pro_detail_note',
		    'column'	=> 'note',
		    'type'		=> 'varchar',
		    'len'		=> 500,
		    'rules'		=> 'max_length[500]',
		    'required'	=> false,
		    'comment' 	=> 'note of promotion detail',
		),
		'tour_id' => array (
		    'field'		=> 'tour_id',
		    'label' 	=> 'tour_id',
		    'column'	=> 'tour_id',
		    'type'		=> 'int',
		    'required'	=> true,
		    'rules'		=> '',
		    'comment' 	=> 'FK->tours: the tour was applied this pro detail',
		),
		'promotion_id' => array (
		    'field'		=> 'promotion_id',
		    'label' 	=> 'promotion_id',
		    'column'	=> 'promotion_id',
		    'type'		=> 'int',
		    'required'	=> true,
		    'comment' 	=> 'FK->promotions',
		),
		'offer_rate' => array (
		    'field'		=> 'offer_rate',
		    'label' 	=> 'lang:pro_detail_offerrate',
		    'column'	=> 'offer_rate',
		    'type'		=> 'tinyint',		    
		    'len'		=> 2,
		    'required'	=> true,		    
		    'comment' 	=> 'the offer rate of a class service',
		),		
		'apply_to' => array (
		    'field'		=> 'apply_to',
		    'label' 	=> 'lang:pro_detail_applyto',
		    'column'	=> 'apply_to',
		    'type'		=> 'varchar',		    
		    'required'	=> false,		    
		    'rules'		=> '',
		    'comment' 	=> 'the tour apply this promotion',
		),				
		'category_id' => array (
		    'field'		=> 'category_id',
		    'label' 	=> 'category_id',
		    'column'	=> 'category_id',
		    'type'		=> 'varchar',		    
		    'required'	=> false,		    
		    'rules'		=> '',
		    'comment' 	=> 'the category of this tour applying',
		),		
		'user_created_id' 	=> array (
		    'field'		=> 'user_created_id',
		    'label' 	=> 'user_created_id',
		    'column'	=> 'user_created_id',
		    'type'		=> 'int',
		    'required'	=> true,
		    'comment' 	=> 'the id of user created this promotion',
		),
		'date_created' 	=> array (
		    'field'		=> 'date_created',
		    'label' 	=> 'date_created',
		    'column'	=> 'date_created',
		    'type'		=> 'datetime',
		    'required'	=> true,
		    'comment' 	=> 'the date this promotion was created',
		),
		'user_modified_id'	=> array (
		    'field'		=> 'user_modified_id',
		    'label' 	=> 'user_modified_id',
		    'column'	=> 'user_modified_id',
		    'type'		=> 'int',
		    'required'	=> true,
		    'comment' 	=> 'the id of user modified this promotion',
		),
		'date_modified' => array (
		    'field'		=> 'date_modified',
		    'label' 	=> 'date_modified',
		    'column'	=> 'date_modified',
		    'type'		=> 'datetime',
		    'required'	=> true,
		    'comment' 	=> 'the last modified of this promotion',
		),
		'deleted' => array (
		    'field'		=> 'deleted',
		    'label' 	=> 'deleted',
		    'column'	=> 'deleted',
		    'type'		=> 'tinyint',
		    'required'	=> true,
		    'comment' 	=> 'mark deleted of this promotion',
		),		
	),
);
/* End of file protination_meta.php */
/* Location: ./system/application/config/protination_meta.php */