<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config = array();
$config['User'] = array(
	'table' => 'users', 
	'audit' =>true,
  	'comment' => 'Store users of the system',
  	'fields' => array (
  		'id' => array (
		    'field'		=> 'id',
		    'label' 	=> 'ID',
		    'column'	=> 'id',		    
		    'type'		=> 'id',
		    'required'	=> true,		    	   
		    'comment' 	=> 'Unique identifier',
		),
		'user_name' => array (
		    'field'		=> 'user_name',
		    'label' 	=> 'lang:user_fields_username',
		    'column'	=> 'user_name',
		    'type'		=> 'varchar',
		    'len'		=> 12,	    
		    'required'	=> true,
		    'rules'		=> 'required|callback__name_check|min_length[3]|max_length[12]',
		    'comment' 	=> 'username of user',
		),
		'password' 	=> array (
		    'field'		=> 'password',
		    'label' 	=> 'lang:user_fields_password',
		    'column'	=> 'password',
		    'type'		=> 'varchar',
		    'len'		=> 12,	    
		    'required'	=> true,
		    'rules'		=> 'required|matches[passconf]|min_length[6]|max_length[12]',
		    'comment' 	=> 'password of user',
		),		
		'status' 	=> array (
		    'field'		=> 'status',
		    'label' 	=> 'lang:user_fields_status',
		    'column'	=> 'status',
		    'type'		=> 'tinyint',
		    'len'		=> 1,	    
		    'required'	=> false,
		    'rules'		=> '',
		    'comment' 	=> 'status of user',
		),		
		'is_admin' => array (
		    'column'	=> 'is_admin',
		    'field'		=> 'is_admin',
		    'label' 	=> 'lang:user_fields_is_admin',
		    'type'		=> 'tinyint',
		    'len'		=> 1,		    
		    'required'	=> false,		    
		    'audit'		=> true,
		    'rules'		=> '',
		    'comment' 	=> 'user or admin',
		),
		'partner_id' => array (
		    'column'		=> 'partner_id',
		    'field'		=> 'partner_id',
		    'label' 	=> 'lang:user_fields_partner',
		    'type'		=> 'int',
		    'len'		=> 11,
		    'required'	=> true,
		    'rules'		=> 'callback__checkPartner',
		    'audit'		=> true,		    
		    'comment' 	=> 'partner_id of user',
		),		
		'date_created' => array (
		    'column'	=> 'date_created',
		    'field'		=> 'date_created',
		    'label' 	=> 'lang:user_fields_date_created',
		    'type'		=> 'datetime',
		    'len'		=> 8,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'date_created of user',
		),
		'user_created_id' => array (
		    'column'	=> 'user_created_id',
		    'field'		=> 'user_created',
		    'label' 	=> 'lang:user_fields_user_created',
		    'type'		=> 'int',
		    'len'		=> 11,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'user_created of user',
		),
		'date_modified' => array (
		    'column'	=> 'date_modified',
		    'field'		=> 'date_modified',
		    'label' 	=> 'lang:user_fields_date_modified',
		    'type'		=> 'datetime',
		    'len'		=> 8,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'date_modified of user',
		),
		'user_modified_id' => array (
		    'column'	=> 'user_modified_id',
		    'field'		=> 'user_modified',
		    'label' 	=> 'lang:user_fields_user_modified',
		    'type'		=> 'int',
		    'len'		=> 11,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'user_modified of user',
		),
		'deleted' => array (
		    'column'	=> 'deleted',
		    'field'		=> 'deleted',
		    'label' 	=> 'lang:user_fields_deleted',
		    'type'		=> 'tinyint',
		    'len'		=> 1,
		    'required'	=> true,
		    'rules'		=> '',
		    'audit'		=> true,		    
		    'comment' 	=> 'deleted of user',
		),
	)
);

/* End of file metadata.php */
/* Location: ./system/application/config/metadata.php */